# Generated by Django 4.2.7 on 2023-12-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
