# Generated by Django 4.2.7 on 2023-12-14 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0018_cart_total_price'),
        ('user', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paymment_type', models.CharField(max_length=100)),
                ('Paymment_date', models.DateField(auto_now_add=True)),
                ('Paymment_status', models.BooleanField(default=False)),
                ('Paymment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceld', 'canceld')], max_length=20)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.paymment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proudct_quantity', models.IntegerField(default=1, help_text='Enter a positive integer for product quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('added_date', models.DateField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='user.orders')),
                ('proudct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartt_items', to='fluxadmin.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartt_items', to=settings.AUTH_USER_MODEL)),
                ('varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxadmin.verients')),
            ],
        ),
    ]
