# Generated by Django 4.2.7 on 2023-12-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orders_add_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.paymment'),
        ),
    ]
