# Generated by Django 4.2.7 on 2023-12-15 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_items_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_itemss', to='user.orders'),
        ),
    ]
