# Generated by Django 4.2.7 on 2023-12-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_order_items_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
