# Generated by Django 4.2.8 on 2023-12-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
