# Generated by Django 4.2.7 on 2024-01-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address_id',
        ),
    ]
