# Generated by Django 4.2.7 on 2024-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_orders_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='fjlsflsajb', max_length=100),
            preserve_default=False,
        ),
    ]
