# Generated by Django 4.2.7 on 2024-01-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='return_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceld', 'canceld'), ('return_initiated', 'return_initiated'), ('returned', 'returned')], default='Processing', max_length=20),
        ),
    ]
