# Generated by Django 4.2.7 on 2024-01-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_wallet_wallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='history',
            field=models.TextField(default='[]', null=True),
        ),
    ]
