# Generated by Django 4.2.7 on 2023-11-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
