# Generated by Django 4.2.7 on 2023-11-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0004_alter_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images/')),
                ('image_2', models.ImageField(upload_to='images/')),
                ('image_3', models.ImageField(upload_to='images/')),
                ('image_4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('product_price', models.IntegerField()),
                ('sale_prce', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('headphone_type', models.CharField(choices=[('over the Ear', 'Over the Ear'), ('on the Ear', 'On the Ear'), ('in the Ear', 'In the Ear')], max_length=20)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxadmin.brand')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxadmin.category')),
            ],
        ),
        migrations.CreateModel(
            name='verients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varient_color', models.ImageField(upload_to='images/')),
                ('quantity', models.IntegerField()),
                ('image_field', models.ManyToManyField(related_name='related_images', to='fluxadmin.images')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varients', to='fluxadmin.product')),
            ],
        ),
    ]
