# Generated by Django 4.2.7 on 2023-11-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0005_images_product_verients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image_4',
        ),
    ]
