# Generated by Django 4.2.7 on 2023-11-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0006_remove_images_image_2_remove_images_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='owner',
            field=models.CharField(default='d', max_length=50),
            preserve_default=False,
        ),
    ]
