# Generated by Django 4.2.7 on 2023-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0009_verients_varient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verients',
            name='varient_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
