# Generated by Django 4.2.7 on 2023-11-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0011_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_date',
            field=models.DateField(default='2003-3-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='cat_date',
            field=models.DateField(default='2002-3-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateField(default='2002-3-3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verients',
            name='varient_date',
            field=models.DateField(default='2002-2-2'),
            preserve_default=False,
        ),
    ]
