# Generated by Django 4.2.7 on 2023-11-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0014_alter_brand_brand_date_alter_category_cat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='f', upload_to='images/'),
            preserve_default=False,
        ),
    ]
