# Generated by Django 4.2.7 on 2023-12-12 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxadmin', '0015_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('proudct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='fluxadmin.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('varient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxadmin.verients')),
            ],
        ),
    ]
