# Generated by Django 4.2.7 on 2023-12-12 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0016_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='proudct_quantity',
            field=models.IntegerField(default=1, help_text='Enter a positive integer for product quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
