# Generated by Django 4.2.7 on 2023-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0017_cart_proudct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
