# Generated by Django 4.2.8 on 2023-12-22 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxadmin', '0018_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('expiary_date', models.DateField()),
                ('coupon_users', models.ManyToManyField(blank=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
