# Generated by Django 4.2.8 on 2023-12-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0020_remove_coupon_coupon_users_coupon_offer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
