# Generated by Django 4.2.8 on 2023-12-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0021_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_per', models.DecimalField(decimal_places=2, max_digits=4)),
                ('starting_date', models.DateField(auto_now_add=True)),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
