# Generated by Django 4.2.8 on 2023-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0022_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='offer_per',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
