# Generated by Django 4.2.7 on 2024-01-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0024_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='special_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=200, unique=True)),
                ('banner_image', models.ImageField(upload_to='images/')),
                ('stat_date', models.DateField()),
                ('end_date', models.DateField()),
                ('offer_per', models.IntegerField()),
            ],
        ),
    ]
