# Generated by Django 4.2.7 on 2024-01-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0025_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_offer',
            name='appied_for',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special_offer',
            name='namee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
