# Generated by Django 4.2.7 on 2024-01-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxadmin', '0026_special_offer_appied_for_special_offer_namee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_applied_products', to='fluxadmin.special_offer'),
        ),
    ]
